name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set Environment Variables
      run: |
        echo "ATCODER_USERNAME=$ATCODER_USERNAME" >>.env
        echo "ATCODER_PASSWORD=$ATCODER_PASSWORD" >>.env
        echo "DB_ENGINE=$DB_ENGINE" >> .env
        echo "DB_NAME=$DB_NAME" >> .env
        echo "DB_USERNAME=$DB_USERNAME" >> .env
        echo "DB_PASSWORD=$DB_PASSWORD" >> .env
        echo "DB_HOST=$DB_HOST" >> .env
        echo "DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY" >> .env
        echo "ALLOWED_HOST=$ALLOWED_HOST" >> .env
        echo "DEBUG=$DEBUG" >> .env
        echo "STATIC_URL=$STATIC_URL" >> .env
      env:
        ATCODER_USERNAME: ${{ secrets.ATCODER_USERNAME }}
        ATCODER_PASSWORD: ${{ secrets.ATCODER_PASSWORD }}
        DB_ENGINE: ${{ secrets.DB_ENGINE }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        ALLOWED_HOST: ${{ secrets.ALLOWED_HOST }}
        DEBUG: ${{ secrets.DEBUG }}
        STATIC_URL: ${{ secrets.STATIC_URL }}
    - name: Set up Database
      run: |
        python manage.py migrate --skip-checks
    - name: Run Tests
      run: |
        python manage.py test
